### PR TITLE
Updated puzl domain

### PR DESCRIPTION
**Pull request by sergeimonakhov**
**What this PR does / why we need it**:

Hello, 
We have updated the puzl domain, please accept the pull request

### CODE REVIEW

**Comment by cwilkers** [comment]
/ok-to-test

By the way, we can't accept a PR without a DCO signoff.

**Comment by cwilkers** [comment]
@aburdenthehand  could you take a look?

**Comment by aburdenthehand** [comment]
/lgtm
Thanks for the PR @sergeimonakhov, and thanks for the ping @cwilkers

**Pull request merged**
