### PR TITLE
Fix istio post linting

### PR DESCRIPTION
**Pull request by tylerauerbeck**
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>

**What this PR does / why we need it**:

This fixes some issues found by the markdown linter in the istio blog post.

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

N/A

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
@mazzystr Looks like a broken link?

```
*  External link https://talks.godoc.org/github.com/jparrill/hands-on-prow/hands-on-prow.slide#1 failed: 500 
```

A bit confused though because it seems to work fine for me.

**Comment by mazzystr** [comment]
@tylerauerbeck I'm good with removing the sentence that contains that link.  

```
$ git diff
diff --git a/_posts/2019-10-31-prow-jobs-for-kubevirt.markdown b/_posts/2019-10-31-prow-jobs-for-kubevirt.markdown
index 493efb37d..aac9ba72c 100644
--- a/_posts/2019-10-31-prow-jobs-for-kubevirt.markdown
+++ b/_posts/2019-10-31-prow-jobs-for-kubevirt.markdown
@@ -24,7 +24,7 @@ tags:

 General PR's, etc are tested by Prow to be validated to be reviewed by doing some sanity checks defined by developers.

-In general, the internals on how it works can be checked at [Life of a Prow Job](https://github.com/kubernetes/test-infra/blob/master/prow/life_of_a_prow_job.md), and of course in the presentation made by [Juanma](https://github.com/jparrill) on <https://talks.godoc.org/github.com/jparrill/hands-on-prow/hands-on-prow.slide#1>.
+In general, the internals on how it works can be checked at [Life of a Prow Job](https://github.com/kubernetes/test-infra/blob/master/prow/life_of_a_prow_job.md).

```

**Pull request merged**
