### PR TITLE
Adding post to link to and socialize the second kubevirt summit

### PR DESCRIPTION
**Pull request by cwilkers**
Creates blog post to ensure summit is in our news feed.

refers to https://github.com/kubevirt/kubevirt.github.io/pull/824

Signed-off-by: cwilkers <cwilkers@redhat.com>

### CODE REVIEW

**Comment by cwilkers** [comment]
@jberkus Here's a blog post, cut mostly from last year's announce post.

**Comment by jberkus** [comment]
/lgtm

I don't have approve rights, tho

**Review by rmohr — APPROVED** [review]
/lgtm

**Comment by rmohr** [comment]
> I don't have approve rights, tho

me neither. Looks good to me too.

**Pull request merged**
