### PR TITLE
adopters: Add missing logos to allow adopters.py automation to work

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

The [adopters.py script](https://github.com/kubevirt/kubevirt.github.io/blob/main/_data/adopters.py) requires the logos of adopters listed in the k/kubevirt adopters file to be in place in order to correctly generate the adopters.yml

The adopters.yml is used to generate the adopters section on the home page of the kubevirt website. 
https://github.com/kubevirt/kubevirt.github.io/blob/cac3e37d480c3f5060ea86a5933100791089fbca/index.html#L45

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:
/cc @aburdenthehand @dhiller

### CODE REVIEW

**Comment by dhiller** [comment]
> **What this PR does / why we need it**:
> 
> **Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
> 
> > Fixes #
> 
> **Special notes for your reviewer**: /cc @aburdenthehand @dhiller

I am not very familiar with how the html page generation and other stuff here work, also I have no idea where adopters.py comes from.

Can you please help me understand this better by adding some links and a bit more explanation in the PR description?

**Comment by aburdenthehand** [comment]
+1 to dhiller's request for a bit more info in the description - especially because it will be helpful to update whatever documentation required to make this process a bit more transparent for the future. It would also be good if we could tie this in better to our adopters process in k/kubevirt.
But this is marvellous work @brianmcarey. 

I see that Alauda is at the bottom of the 'end users' (https://deploy-preview-978--kubevirtio.netlify.app/). Looking at the k/kubevirt adopters file i see that they are at the bottom of the file. Is there a way to enforce alphabetical listing of logos in the adopters.py script, or should we rely on humans and an instruction when adding adopters in k/kubevirt? (I am culpable of missing it in this case)

If it's not a bother I'm going to hold this until we fix the adopters file in k/kubevirt so we don't need to re-run the script for a new PR. 

/hold

**Comment by brianmcarey** [comment]
> > **What this PR does / why we need it**:
> > **Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
> > > Fixes #
> > 
> > 
> > **Special notes for your reviewer**: /cc @aburdenthehand @dhiller
> 
> I am not very familiar with how the html page generation and other stuff here work, also I have no idea where adopters.py comes from.
> 
> Can you please help me understand this better by adding some links and a bit more explanation in the PR description?

@dhiller I have updated the PR description now. 

Leaving the hold in place as I am expecting to have to rebase due to some of the recent changes going in like - https://github.com/kubevirt/kubevirt.github.io/pull/974 & https://github.com/kubevirt/kubevirt/pull/13319

**Comment by brianmcarey** [comment]
@aburdenthehand the order should be correct now since the update of the  ADOPTERS in kubevirt has been merged - https://github.com/kubevirt/kubevirt/pull/13319

**Comment by aburdenthehand** [comment]
/unhold
/lgtm
Nice one, thanks @brianmcarey

**Review by dhiller — APPROVED** [review]
/approve

Thank yo @brianmcarey - awesome fix!

**Pull request merged**
