### PR TITLE
Update quickstart_cloud.md

### PR DESCRIPTION
**Pull request by serewicz**
If someone does a copy and paste too fast there is no output. It takes a bit for the deployment to be running in order to see output.

**What this PR does / why we need it**:

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:
Tried this once already. Didn't see it go through. Trying a second time.

### CODE REVIEW

**Comment by serewicz** [comment]
Hello,

How do I add the DCO signoff now that I already did the commit. Should I revoke the commit and do something else?

**Comment by jobbler** [comment]
I checked the preview and this looks good to me
/lgtm

**Comment by serewicz** [comment]
Hello,  Sorry to be a total newb, but when I click on the "Details" link on the dco it throws a 404 error. Advice on adding the dco appreciated. What else should I be doing for this?  Thanks.

**Comment by jobbler** [comment]
@serewicz You need to sign your commits.
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Since you already committed this one, you should be ablt to ammend it.
`git commit -S --ammend`

I got this command from https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

**Pull request closed without merging**
