### PR TITLE
Add new vendor puzl.ee

### PR DESCRIPTION
**Pull request by netmenya**
**What this PR does / why we need it**:
This PR adds puzl.ee as a vendor to `index.html`

### CODE REVIEW

**Comment by mazzystr** [comment]
@netmenya Looks good!

I just have a small (but might be big) legal question to ask.  Are you puzl.ee's representative and have you sought approval from puzl.ee's legal/marketing team to allow KubeVirt to publish the corp logo?  If so can you or a corp representative post a comment saying that puzl.ee gives approval to publish the logo?

**Comment by netmenya** [comment]
> Are you puzl.ee's representative and have you sought approval from puzl.ee's legal/marketing team to allow KubeVirt to publish the corp logo?

@mazzystr I'm a Puzl.ee's representative. 

Puzl.ee gives approval to publish the logo.

**Comment by mazzystr** [comment]
Thank you.  That's all we need.  And welcome aboard!

/lgtm
/approve

**Comment by netmenya** [comment]
@mazzystr Thank you!

**Pull request merged**
