### PR TITLE
Update the install guide with the addition of installing via `krew`

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Update the install guide with the addition of installing `virtctl` via [`krew`](https://krew.dev/)

**Does this PR fix any issue?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
> Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dhiller** [comment]
Rebase done. @iranzo @karmab please review again.

**Comment by iranzo** [comment]
Waiting on https://github.com/kubevirt/kubevirt.github.io/pull/255 to get merged to fix the CI test

**Pull request merged**
