### PR TITLE
Corrected markdown lint

### PR DESCRIPTION
**Pull request by cwilkers**
Signed-off-by: cwilkers <cwilkers@redhat.com>

**What this PR does / why we need it**:

With the check_lint working, I was able to find a few pages that have sneaked in with non-ideal formatting.

**Does this PR fix any issue?** 

No issue, just opportunity when correcting the Dockerfile in https://github.com/kubevirt/project-infra/pull/2189

**Special notes for your reviewer**:

I left one piece of lint I don't fully agree is a problem. It might be nice to disable that rule properly at some point.

### CODE REVIEW

**Review by aburdenthehand — APPROVED** [review]
Everything seems to be in line. Thank you!

**Review by phoracek — APPROVED** [review]
/approve

**Pull request merged**
