### PR TITLE
Add netlify usage to privacy page

### PR DESCRIPTION
**Pull request by iranzo**
**What this PR does / why we need it**:

**Does this PR fix any issue?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
> Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by codificat** [comment]
netlify integration was enabled in the repo
/hold cancel

**Comment by iranzo** [comment]
Reuploading to trigger DCO

**Comment by iranzo** [comment]
Preview of change already available at: https://deploy-preview-324--kubevirtio.netlify.com/privacy/


Was resubmitted for passing DCO

**Pull request merged**
