### PR TITLE
Fix broken code block

### PR DESCRIPTION
**Pull request by charlesritchea**
Fixes broken code block in installation guide

### CODE REVIEW

**Comment by cwilkers** [comment]
Thanks for the PR, I'll okay testing, but I think you may still need a bare newline between previous text and the code block. Once the automated tests run, we can check a test render of the page to verify.

Also, in order to be accepted, you will need to sign your commit. This is a simple amend commit with a force push, like this:

git commit --amend --signoff
git push --force

/ok-to-test

**Comment by cwilkers** [comment]
Please see my earlier note about the signoff requirement.

/retest

**Comment by charlesritchea** [comment]
Sorry I don't have time for this right now, this was simply the best way I
thought I could notify the project team of the broken docs

**Comment by cwilkers** [comment]
> Sorry I don't have time for this right now, this was simply the best way I thought I could notify the project team of the broken docs

That's alright, it happens. Thanks for letting us know.

Since I really can't get the system to accept the PR without sign-off, I'll close this PR and create a new one. Also, issues are better than PRs in this regard, because then somebody else can create and shepherd the fix even if the original reporter does not have spare cycles to do so.

**Comment by cwilkers** [comment]
Actually, now that I look at this, the only place where it renders incorrectly is within github. The webpage that includes this snippet renders just fine.

**Comment by charlesritchea** [comment]
I've forgotten the original context and didn't end up using kube-virt, so I'm not vested anymore, but Markdown codeblocks with three backticks are part of GFM (GitHub Flavored Markdown) and they don't have spaces before the backticks. There is an alternative code block method where everything is indented, but again doesn't apply to the backticks. So, great if it works for you, but I wouldn't continue doing that as a pattern

**Pull request closed without merging**
