### PR TITLE
Update copyright footer

### PR DESCRIPTION
**Pull request by celestehorgan**
This PR builds on https://github.com/kubevirt/kubevirt.github.io/pull/567 and addresses feedback from that PR.

### CODE REVIEW

**Comment by fabiand** [comment]
Thanks Celeste.

@mazzystr can you help to resolve the issue here?

**Comment by mazzystr** [comment]
@fabiand  finally back from pto ... yup, I am on it.  

@celestehorgan I'm looking at Netlify and reviewing this now.

**Comment by celestehorgan** [comment]
@mazzystr The build fails with a non-specific error code, and some googling doesn't reveal much. Maybe, before doing anything, try retriggering the Netlify build? (I can't do this with my level of permissions :))

**Comment by mazzystr** [comment]
Netlify has definitely been funky in the last week or so.  I have no idea where these bad url's are coming from.  I'm working on the investigation.

**Comment by celestehorgan** [comment]
Hmm. I wonder if there's a bad change that got merged in somehow? Let me
know how it goes 🙂

**Comment by mazzystr** [comment]
@celestehorgan I figured it out... The last commit on your branch is _commit ed3d40a3 on Thu May 28_.  Those urls were indeed broken back then.  Please rebase by doing the following...
1) Ensure you have the correct upstream remote configured.  Run:
```
git remote -v
origin	git@github.com:celestehorgan/kubevirt.github.io.git (fetch)
origin	git@github.com:celestehorgan/kubevirt.github.io.git (push)
upstream	git@github.com:kubevirt/kubevirt.github.io.git (fetch)
upstream	git@github.com:kubevirt/kubevirt.github.io.git (push)
```
if your upstream doesn't look like this then run `git remote rm upstream`
Ensure the correct upstream is created.  Run `git remote add upstream git@github.com:kubevirt/kubevirt.github.io.git`

2) Update your branch by rebasing and pushing.  Run:
```
git checkout copyright-footer-2
git rebase upstream/source
git push origin
```
Rebasing can be pretty awful. I changed my upstream to your fork and tested.  Branch copyright-footer-2 rebased without  issue.  If git complains for you and you need help feel free to post a comment in GitHub or ping me in Kubernetes Slack / #virtualization and I can work with you further.

I'll peer review your content when we get successful CI.

Thanks.

**Comment by celestehorgan** [comment]
At this point this branch is far enough behind that it's probably easier to close and re-open this PR, so that's what i'll do :)

**Comment by celestehorgan** [comment]
Update: checking `source`, this doesn't seem to be an update that's still needed. Closing forever, thank you all!

**Pull request closed without merging**
