### PR TITLE
Deprecate OCP Labs which are not mantained

### LINKED ISSUE #254: OpenShift lab might be out of date
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

There is an OpenShift lab (labeled "OCP lab") in https://kubevirt.io/labs/ocp that seems to be out of date

**What you expected to happen**:

The lab should be updated or removed as appropriate

**Anything else we need to know?**:

The lab appears to have been originally based on the [kubevirt-tutorial](https://github.com/kubevirt/kubevirt-tutorial). That tutorial has evolved, is now based on Kubernetes - maybe it's worth doing a joint review.

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

### LINKED ISSUE #273: OCP Labs are hidden and require fixes
**Is this a BUG REPORT or FEATURE REQUEST?**:

OCP Labs are in the source code for website, but not listed on https://kubevirt.io/labs/kubernetes/lab1.html

When updating _data/labs_toc.yml to list them they now appear, but require some other fixes as there are broken links to images that are no longer there

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

### PR DESCRIPTION
**Pull request by iranzo**
**What this PR does / why we need it**:

Closes #273
Closes #254 

**Does this PR fix any issue?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
> Fixes #

**Special notes for your reviewer**:

/kind bug
/wip

### CODE REVIEW

**Comment by codificat** [comment]
Shouldn't we remove that content instead?

**Comment by iranzo** [comment]
That's why this is still on hold, to wait until the labs are fixed and then, show them

**Pull request merged**
