### PR TITLE
Fix kubernetes-nmstate links

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
The links referenced in NNCP section are wrong; this commit updates
them.

### CODE REVIEW

**Comment by qinqon** [comment]
Thanks, now we have a project page for it, https://www.nmstate.io/kubernetes-nmstate/, it would be even better to point to it instead of github master, but only if you want to do it, fixing like you do is good enough.

**Comment by codificat** [comment]
> Thanks, now we have a project page for it, https://www.nmstate.io/kubernetes-nmstate/, it would be even better to point to it instead of github master, but only if you want to do it, fixing like you do is good enough.

I see that the project page is already linked from the previous paragraph, so this should hopefully be fine.
/approve

**Pull request merged**
