### PR TITLE
Ansible modules introduction, part2

### PR DESCRIPTION
**Pull request by mmazur**

### CODE REVIEW

**Comment by iranzo** [comment]
The internal link to the other post should be like {% post_url $NAMEOFTHEFILEWITHOUTEXTENSION %}

**Comment by iranzo** [comment]
@mmazur is this still considered wip right?

**Comment by iranzo** [comment]
Ok, let's remove then WIP for both articles, I'll take care of getting it done

**Comment by iranzo** [comment]
@tripledes all yours bear in mind when rendering the generated file, that it will be 'hidden' until 8th july, so check the filename and yaml preamble data for live preview of it

**Comment by mmazur** [comment]
No no, this one is actually WIP, it's missing a bit in the middle. I'll fill it out tomorrow morning and remove the WIP again. #284 is the one that can be merged today.

**Comment by mmazur** [comment]
Nope, me from 25 minutes ago was mistaken, this is ready for review.

**Comment by iranzo** [comment]
Hi,
I'm replacing some links to use the macro for avoiding problems in the future {% post_url article %}

And I've doubts on the link to 'datavolumes/introductory blog post' that links to 'attaching-to-multiple-networks', it should be '2018-10-10-CDI-DataVolumes' right?

Thanks @mmazur !

PD: I'll post a commit on top of yours to replace the links for the macros so that I can include this one too

**Comment by iranzo** [comment]
~~~diff
diff --git a/_posts/2019-07-08-kubevirt-with-ansible-part-2.markdown b/_posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
index 7bf7c32..dfb4299 100644
--- a/_posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
+++ b/_posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
@@ -13,13 +13,13 @@ comments: true
 [Part 1][blog part 1] contained a short introduction to basic VM management with Ansible's `kubevirt_vm` module.
 This time we'll paint a more complete picture of all the features on offer.
 
-As before, examples found herein are also available as full working playbooks in our 
-[playbooks example repository][blog examples]. 
+As before, examples found herein are also available as full working playbooks in our
+[playbooks example repository][blog examples].
 Additionally, each section of this post links to the corresponding module's Ansible documentation page.
-Those pages always contain an _Examples_ section, which the reader is encouraged to look through, as they have 
+Those pages always contain an _Examples_ section, which the reader is encouraged to look through, as they have
 many more ways of using the modules than can reasonably fit here.
 
-[blog part 1]: https://kubevirt.io/2019/kubevirt-with-ansible-part-1.html
+[blog part 1]: {% post_url 2019-05-21-kubevirt-with-ansible-part-1 %}
 [blog examples]: https://github.com/kubevirt/ansible-kubevirt-modules/tree/master/examples/blog
 
 
@@ -34,17 +34,17 @@ Virtual machines managed by KubeVirt are highly customizable. Among the features
 * direct DataVolumes support (`datavolumes`),
 * and OpenShift Templates support (`template`).
 
-[datavols]: https://kubevirt.io/2018/CDI-DataVolumes.html
+[datavols]: {% post_url 2018-10-10-CDI-DataVolumes %}
 
 ### Further resources
 
 * [Ansible module documentation](https://docs.ansible.com/ansible/latest/modules/kubevirt_vm_module.html)
   * [Examples, lots of examples](https://docs.ansible.com/ansible/latest/modules/kubevirt_vm_module.html#examples)
 * DataVolumes
-  * [Introductory blog post](https://kubevirt.io/2018/attaching-to-multiple-networks.html)
+  * [Introductory blog post]({% post_url 2018-10-10-CDI-DataVolumes %})
   * [Upstream documentation](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/datavolumes.md)
 * Multus
-  * [Introductory blog post](https://kubevirt.io/2018/attaching-to-multiple-networks.html)
+  * [Introductory blog post]({% post_url 2018-09-12-attaching-to-multiple-networks %})
   * [GitHub repo](https://github.com/intel/multus-cni)
 
 
@@ -206,4 +206,3 @@ VM presets to be used by deployed VMs,
 templating mechanism, when running on top of OpenShift or OKD,
 * and [kubevirt_rs](https://docs.ansible.com/ansible/latest/modules/kubevirt_rs_module.html) lets one configure KubeVirt's
 own ReplicaSets for running multiple instances of a specified virtual machine.

~~~

**Comment by iranzo** [comment]
/hold

/approve

Holding until 8th july to merge together with #284

**Pull request merged**
