### PR TITLE
update containerDisk image to use quay.io

### PR DESCRIPTION
**Pull request by ashleyschuett**
**What this PR does / why we need it**:

The image no longer exists on docker hub as we are now using quay.io

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by codificat** [comment]
Hey @ashleyschuett, can you DCO-sign your commit so it can get merged?
Thanks!

**Comment by ashleyschuett** [comment]
Sorry about that! updated, thank you!

**Review by mazzystr — APPROVED** [review]

**Pull request merged**
