### PR TITLE
Add phoracek to owners

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horáček <phoracek@redhat.com>

**What this PR does / why we need it**:

I'd like to request an approve rights to help with reviewes and
maintenance.

Referrals:
- @fabiand

### CODE REVIEW

**Comment by phoracek** [comment]
@cwilkers I don't think the link-checker failure is related to this diff, could it be?

**Comment by fabiand** [comment]
@mazzystr there seems to be a ci issue for the presubmit link checker, can you take a look at it?

Manually merging this to unblock pter.

**Pull request merged**
