### PR TITLE
Update description field for 2021-04-30-intel-vgpu-kubevirt blog post

### PR DESCRIPTION
**Pull request by xphyr**
**What this PR does / why we need it**:

Fixes an oversight in the blog post where I left the "example" description for the blog post in place. Current description does not look good on blog post listing page.

### CODE REVIEW

**Comment by mazzystr** [comment]
/lgtm
Approve

**Comment by mazzystr** [comment]
@xphyr you're finally merged

**Comment by xphyr** [comment]
Ok thanks. Fyi @mazzystr it does not appear to have updated the site itself. The site still shows 'excerpt of the blog post' or something like that

**Comment by mazzystr** [comment]
@xphyr Can you post a screenshot so I can see what you're seeing? 

The code in master branch looks correct to me....
https://github.com/kubevirt/kubevirt.github.io/blob/master/2021/intel-vgpu-kubevirt.html#L38

The rendered and served code looks correct to me....
Web browse to https://kubevirt.io/2021/intel-vgpu-kubevirt.html
Open up dev tools
Web browser word search for "Description"  .... Again I see the Description patch

**Comment by xphyr** [comment]
Looks good now. Must have taken some time to populate. Thanks again!

**Comment by mazzystr** [comment]
Whew!  Good to hear!

It also looks like we have an auto publishing problem for future dated blog posts.  Thanks for bringing that to our attention.  We will be working on it on the back end.

**Pull request merged**
