### PR TITLE
Tooling

### PR DESCRIPTION
**Pull request by mazzystr**
**What this PR does / why we need it**:
* Update to remove userguide items
* Squashed a bug regarding envvar target and bad env var testing
* Testing path for casperjs test file leaked in.  Fixed.

Test 1 / show yaspeller in action
```
# make check_spelling

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Check spelling on site content
Dictionary file: https://raw.githubusercontent.com/kubevirt/project-infra/master/images/yaspeller/.yaspeller.json

Spelling check:
✗ /srv/_posts/2021-01-12-KubeVirt-Summit-announce.md 433 ms
-----
Typos: 1
1. CET (26:59, suggest: CAT, CUT, SET, CENT)
-----

✗ /srv/pages/summit.md 397 ms
-----
Typos: 1
1. CET (23:59, suggest: CAT, CUT, SET, CENT)
-----

make: *** [Makefile:133: check_spelling] Error 1
```

Test 2 / show problems curl file or incorrect json 
```
# make check_spelling

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Check spelling on site content
Dictionary file: https://raw.githubusercontent.com/kubevirt/project-infra/master/images/yaspeller/.yaspeller.json
Unable to curl yaspeller dictionary file
yaspeller dictionary file does not exist or is invalid json
make: *** [Makefile:133: check_spelling] Error 1
```

Test 3 / show yaspeller not finding any problems
```
[root@fedora website]# rm pages/summit.md  _posts/2021-01-12-KubeVirt-Summit-announce.md
rm: remove regular file 'pages/summit.md'? y
rm: remove regular file '_posts/2021-01-12-KubeVirt-Summit-announce.md'? y
[root@fedora website]# make check_spelling

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Check spelling on site content
Dictionary file: https://raw.githubusercontent.com/kubevirt/project-infra/master/images/yaspeller/.yaspeller.json

Spelling check:
Complete!
```

Test 3 / show check_links not finding any problems
```
# make check_links

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Check external, internal links on website content

Building...
bundle exec jekyll build
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kubevirt.html
                     - tag/kubevirt.html
                     - tag/kubevirt.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/ovirt.html
                     - tag/ovirt.html
                     - tag/ovirt.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kvm.html
                     - tag/kvm.html
                     - tag/kvm.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/qemu.html
                     - tag/qemu.html
                     - tag/qemu.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/ci-cd.html
                     - tag/ci-cd.html
                     - tag/ci-cd.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/cdi.html
                     - tag/cdi.html
                     - tag/cdi.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kubecon.html
                     - tag/kubecon.html
                     - tag/kubecon.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/condition-types.html
                     - tag/condition-types.html
                     - tag/condition-types.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kubernetes.html
                     - tag/kubernetes.html
                     - tag/kubernetes.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/okd.html
                     - tag/okd.html
                     - tag/okd.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/windows.html
                     - tag/windows.html
                     - tag/windows.html

                    done in 6.634 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

Checks html files for broken external links (This can take a few mins to run) ...
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...


Checking 1025 external links...
Ran on 358 files!


HTML-Proofer finished successfully.

Checks html files for broken internal links (This can take a few mins to run) ...
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...


Ran on 358 files!


HTML-Proofer finished successfully.

Makefile: Check links and selectors to userguide on website content
make[1]: Entering directory '/opt/git/kubevirt/user-guide'

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo

Makefile: Run site
podman run -d --name userguide --net=host -v ./:/srv:ro --mount type=tmpfs,destination=/srv/site localhost/userguide:latest /bin/bash -c "mkdocs build -f /srv/mkdocs.yml && mkdocs serve -f /srv/mkdocs.yml -a 0.0.0.0:8000"
eb6ddeebb13e1b9a6f9ff453e48c9055c10ee3a559a3b75a7a66e3066c117c00

make[1]: Leaving directory '/opt/git/kubevirt/user-guide'
File: ./_site/2020/Advanced-scheduling-with-affinity-rules.html
Link: https://kubevirt.io/user-guide/operations/node_assignment/#affinity-and-anti-affinity
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.862s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/operations/node_assignment/#nodeselector
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.778s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/Live-migration.html
Link: https://kubevirt.io/user-guide/operations/node_maintenance/#evict-all-vms-from-a-node
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.823s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/KubeVirt_storage_rook_ceph.html
Link: https://kubevirt.io/user-guide/operations/virtctl_client_tool/#retrieving-the-virtctl-client-tool
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.761s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/labs/kubernetes/lab1.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.157s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#emptydisk
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.127s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#ephemeral
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.986s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#persistentvolumeclaim
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.072s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/lifecycle/#stopping-a-virtual-machine
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.088s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/presets/#examples
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.888s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/presets/#virtualmachine-selector
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.87s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/replicaset/#example
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.865s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/replicaset/#using-virtualmachineinstancereplicaset
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.768s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/Customizing-images-for-containerized-vms.html
Link: https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.873s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init-examples
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.893s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#clock
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.815s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#cpu
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.829s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#features
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.789s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#machine-type
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.822s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#resources-requests-and-limits
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.786s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#timers
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.804s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_machine_instances/#virtualmachineinstance-api
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.757s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/More-about-Kubevirt-metrics.html
Link: https://kubevirt.io/user-guide/operations/component_monitoring/#custom-service-discovery
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.746s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/More-about-Kubevirt-metrics.html
Link: https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.683s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/NodeDrain-KubeVirt.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_machine_instances/#virtual-machines-instances
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.68s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html
Link: https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/#how-to-obtain-virtio-drivers
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.79s, 1 passed, 0 failed, 0 dubious, 0 skipped.

make[1]: Entering directory '/opt/git/kubevirt/user-guide'

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo
eb6ddeebb13e1b9a6f9ff453e48c9055c10ee3a559a3b75a7a66e3066c117c00

make[1]: Leaving directory '/opt/git/kubevirt/user-guide'
Complete!

[root@fedora website]#
```

Test 4 /show check_links finding a problem
```
# make check_links

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Check external, internal links on website content

Building...
bundle exec jekyll build
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kubevirt.html
                     - tag/kubevirt.html
                     - tag/kubevirt.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/ovirt.html
                     - tag/ovirt.html
                     - tag/ovirt.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kvm.html
                     - tag/kvm.html
                     - tag/kvm.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/qemu.html
                     - tag/qemu.html
                     - tag/qemu.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/ci-cd.html
                     - tag/ci-cd.html
                     - tag/ci-cd.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/cdi.html
                     - tag/cdi.html
                     - tag/cdi.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kubecon.html
                     - tag/kubecon.html
                     - tag/kubecon.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/condition-types.html
                     - tag/condition-types.html
                     - tag/condition-types.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/kubernetes.html
                     - tag/kubernetes.html
                     - tag/kubernetes.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/okd.html
                     - tag/okd.html
                     - tag/okd.html

          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /srv/jekyll/_site/tag/windows.html
                     - tag/windows.html
                     - tag/windows.html

                    done in 6.707 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

Checks html files for broken external links (This can take a few mins to run) ...
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...


Checking 1026 external links...
Ran on 358 files!


HTML-Proofer finished successfully.

Checks html files for broken internal links (This can take a few mins to run) ...
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html...


Ran on 358 files!


HTML-Proofer finished successfully.

Makefile: Check links and selectors to userguide on website content
make[1]: Entering directory '/opt/git/kubevirt/user-guide'

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo

Makefile: Run site
podman run -d --name userguide --net=host -v ./:/srv:ro --mount type=tmpfs,destination=/srv/site localhost/userguide:latest /bin/bash -c "mkdocs build -f /srv/mkdocs.yml && mkdocs serve -f /srv/mkdocs.yml -a 0.0.0.0:8000"
138fcdadff7d9fec9062a2bb2d035b40fcb7b48e4cf0e29b73621657301778bd

make[1]: Leaving directory '/opt/git/kubevirt/user-guide'
File: ./_site/2019/More-about-Kubevirt-metrics.html
Link: https://kubevirt.io/user-guide/operations/component_monitoring/#custom-service-discovery
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.743s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/More-about-Kubevirt-metrics.html
Link: https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.67s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/Advanced-scheduling-with-affinity-rules.html
Link: https://kubevirt.io/user-guide/operations/node_assignment/#affinity-and-anti-affinity
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.697s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/operations/node_assignment/#nodeselector
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.736s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/Live-migration.html
Link: https://kubevirt.io/user-guide/operations/node_maintenance/#evict-all-vms-from-a-node
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.697s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/KubeVirt_storage_rook_ceph.html
Link: https://kubevirt.io/user-guide/operations/virtctl_client_tool/#retrieving-the-virtctl-client-tool
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.669s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/lifecycle/#stopping-a-virtual-machine
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.673s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/replicaset/#example
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.703s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/replicaset/#using-virtualmachineinstancereplicaset
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.732s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/Customizing-images-for-containerized-vms.html
Link: https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.803s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init-examples
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.853s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#clock
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.906s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#cpu
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.82s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#features
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.813s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#resources-requests-and-limits
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.782s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#timers
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.819s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2019/NodeDrain-KubeVirt.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_machine_instances/#virtual-machines-instances
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.707s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_machine_instances/#virtualmachineinstance-api
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.636s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html
Link: https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/#dfghfgh
Test file: /srv/jekyll/check_selectors.js
#    type: assertExists
#    file: /srv/jekyll/check_selectors.js
#    subject: false
#    selector: "#dfghfgh"
⚠  --fail-fast: aborted all remaining tests
FAIL 1 test executed in 0.704s, 0 passed, 1 failed, 0 dubious, 0 skipped.

Details for the 1 failed test:

In /srv/jekyll/check_selectors.js
  file: ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html, url: https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/#dfghfgh
    assertExists: Find selector: #dfghfgh
FAIL 1 test executed in 0.704s, 0 passed, 1 failed, 0 dubious, 0 skipped.

Details for the 1 failed test:

In /srv/jekyll/check_selectors.js
  file: ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html, url: https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/#dfghfgh
    assertExists: Find selector: #dfghfgh

File: ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html
Link: https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/#how-to-obtain-virtio-drivers
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.74s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/labs/kubernetes/lab1.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.036s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#emptydisk
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#ephemeral
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.012s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#persistentvolumeclaim
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 1.012s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/presets/#examples
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.797s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/presets/#virtualmachine-selector
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.864s, 1 passed, 0 failed, 0 dubious, 0 skipped.

File: ./_site/2018/KubeVirt-objects.html
Link: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#machine-type
Test file: /srv/jekyll/check_selectors.js
PASS 1 test executed in 0.853s, 1 passed, 0 failed, 0 dubious, 0 skipped.

make[1]: Entering directory '/opt/git/kubevirt/user-guide'

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo
138fcdadff7d9fec9062a2bb2d035b40fcb7b48e4cf0e29b73621657301778bd

make[1]: Leaving directory '/opt/git/kubevirt/user-guide'
Complete!
```
Makefile should exit 1 if casperjs finds a problem.  I think think I want to issue that.  This pull_req is already big.

### CODE REVIEW

**Comment by mazzystr** [comment]
@codificat

**Comment by mazzystr** [comment]
@codificat Please test and merge

**Comment by mazzystr** [comment]
test comment

**Comment by mazzystr** [comment]
@fabiand @davidvossel  Would one of you guys lgtm / approve me.  This pull req is holding up some other work on the repo.

**Comment by mazzystr** [comment]
@fabiand @davidvossel Would one of you guys lgtm / approve me. This pull req is holding up some other work on the repo.

Let's try `Comment` and not `Close with comment` this time

**Comment by codificat** [comment]
> This pull req is holding up some other work on the repo.

and you mentioned this was verified locally, so let's ship it
/lgtm
/approve

**Pull request merged**
