### PR TITLE
License

### PR DESCRIPTION
**Pull request by iranzo**
**What this PR does / why we need it**:
Update our website license, code of conduct, etc

Current license is 'MIT based' but it's a verbatim copy of MIT license

CNCF requires some steps covered like code of conduct, etc to be defined

Additionally Netlify requires also to get a form submitted before march indicating code of conduct, license, etc for projects that use the free tier

https://groups.google.com/forum/#!searchin/kubevirt-dev/license%7Csort:date/kubevirt-dev/JTxIBEvvLsE/U54E9WMBDAAJ

### CODE REVIEW

**Comment by rmohr** [comment]
I am ok with this change, but I am not sure how many of the contributors need to agree to this change.

**Comment by slintes** [comment]
A note in the PR description would be nice with an explanation on why this license change is done

**Comment by ptrnull** [comment]
@stu-gott @codificat how do we proceed?

**Comment by ptrnull** [comment]
@stu-gott @codificat @fabiand how do we proceed? we need some support in here.

**Comment by codificat** [comment]
This was raised in the mailing list a while ago, and also in 2 community meetings.

There was no backing to change the license of the web site, so I would suggest that we close this.

Even if the license doesn't change, I believe that the copyright note in the license file should be updated. This was part of this PR, but as the scope is quite different I created a much smaller/specific PR for that, see #546.

**Comment by codificat** [comment]
The copyright note was updated, and we're not re-licensing the content at this time, so we can
/close

**Pull request closed without merging**
