### PR TITLE
Addition of summit co-presentors

### PR DESCRIPTION
**Pull request by davidvossel**
Alex and Cheng will be co-presenting with me during my talk. I added their names to the schedule.

### CODE REVIEW

**Comment by jberkus** [comment]
/lgtm

Can someone merge this?  I have other schedule changes to make.

**Comment by davidvossel** [comment]
/approve

I can't do lgtm for a pr i made

**Comment by jberkus** [comment]
Because this was pending, I added the co-presenters into my PR.

**Pull request closed without merging**
