### PR TITLE
Updates to ansible post part 1

### PR DESCRIPTION
**Pull request by mmazur**
Some edits, to be merged after #283

### CODE REVIEW

**Comment by iranzo** [comment]
@mmazur is this still considered wip right?

**Comment by mmazur** [comment]
@iranzo this is WIP because the CI will fail on a link to part 2 until part 2 gets published. If you're fine merging this with the link pointing to a 404 for the time being, then I'm fine with this not being a WIP.

**Comment by iranzo** [comment]
Ok, let's remove then WIP for both articles, I'll take care of getting it done

**Comment by iranzo** [comment]
/hold
/lgtm
/approve

Holding until 8th july to trigger republish of both articles (part 2 #283 ) and this one linking to part2, link checker will fial in the meantime until 2 is merged

**Pull request merged**
