### PR TITLE
Change Sandbox to Incubating in footer.html

### PR DESCRIPTION
**Pull request by Hiiirad**
**What this PR does / why we need it**:

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jobbler** [comment]
/lgtm
Checked the preview. Thanks for updating this.

**Comment by mazzystr** [comment]
@Hiiirad  Can you please rebase and create the commit with the `git -s` arg?  That adds your signature to the commit message and allows CI to pass the dco check.  Thanks!

**Comment by Hiiirad** [comment]
> @Hiiirad Can you please rebase and create the commit with the `git -s` arg? That adds your signature to the commit message and allows CI to pass the dco check. Thanks!

I did sign the commit with `git commit -S` command. I don't know why this happened. Do you want me to close this PR and do it again?

**Comment by mazzystr** [comment]
DCO can really be a pain in the butt.  I'm not sure why it isn't picking up on your signature.  

Try recreating the PR.  Make sure your commit log looks like this... https://github.com/kubevirt/user-guide#sign-your-commits ... before creating the pull request.

**Pull request closed without merging**
