### PR TITLE
Update summit times and registration details

### PR DESCRIPTION
**Pull request by codificat**
**What this PR does / why we need it**:

Updated information about the summit.

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hroyrh** [comment]
Looks good.
/lgtm
/approve

**Comment by codificat** [comment]
/hold
spotted a typo in the preview

**Comment by codificat** [comment]
/retest
apparently some temporary DNS issues during link checking

**Pull request merged**
