### PR TITLE
Adding our sponsor logos to the summit page.

### PR DESCRIPTION
**Pull request by aburdenthehand**
Civo, Red Hat, and SUSE have stepped forward as sponsors for KubeVirt Summit this year. 
This PR adds their logo to our summit page (as per their level of sponsorship).

### CODE REVIEW

**Review by brianmcarey — APPROVED** [review]
/lgtm

/approve

**Comment by aburdenthehand** [comment]
Also adding CIVO as sponsor

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by fabiand** [comment]
/hold

1. CIVO is also included. The PR should mention this in the description
2. Can we add a line about how they sponsor summit?


But great to see this!

**Comment by aburdenthehand** [comment]
/hold cancel
FYI @fabiand, as this PR now includes what you asked for

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
