### PR TITLE
Fix minikube -> kind typo

### PR DESCRIPTION
**Pull request by tylerauerbeck**
**What this PR does / why we need it**:

This fixes a small typo that mentions a minikube instance inside of the KinD docs

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by codificat** [comment]
Many thanks for spotting this and providing the fix.

/lgtm
/approve

**Comment by codificat** [comment]
Ah, I just noticed that the spell checker is complaining about the capitalization you provided for _KinD_ ... the page just uses an all lowercase (or initial capital at sentence start), which seems consistent with what the [kind website](https://kind.sigs.k8s.io/) uses.

@tylerauerbeck can you adjust the fix and use `Kind` instead of `KinD`?

**Comment by tylerauerbeck** [comment]
@codificat No problem. This should be in good shape now.

**Comment by mazzystr** [comment]
/lgtm
/approve

Thanks for the catch!

**Pull request merged**
