### PR TITLE
feat(redesign): redesign of KubeVirt.io

### PR DESCRIPTION
**Pull request by mindreeper2420**
This PR is for the redesign of KubeVirt.io. Currently in development, a demo of the work can be seen here: http://kvdeml-kv-demo.1d35.starter-us-east-1.openshiftapps.com/.

The design document can be found here: [KubeVirt.io Design](https://redhat.invisionapp.com/share/EDLNEUAN2FY#/screens)

As part of the redesign, the following features are being added:
- discussions on blog posts through Disqus
- a live Twitter feed

### CODE REVIEW

**Comment by scollier** [comment]
@mindreeper2420 Nice work here!  

I noticed that the disqus comment section wasn't enabled on each blog post.  For example, it's here:

http://kvdeml-kv-demo.1d35.starter-us-east-1.openshiftapps.com/2018/KVM-Using-Device-Plugins.html

but not here:

http://kvdeml-kv-demo.1d35.starter-us-east-1.openshiftapps.com/2018/Non-Dockerized-Build.html

**Comment by mindreeper2420** [comment]
@scollier I did that just to test out having some pages with comments and some without. Also to make sure it was something we wanted before going back and adding it to all of the blogs. I'll add Disqus to all of them as part of my next update, now that I know it worked as intended.

I've enabled it through a simple trigger, so any blog post can have comments or not, depending on the type of post.

**Comment by mindreeper2420** [comment]
In the latest update, I've add the Disqus piece to each blog post, update the Readme to include instructions for adding Posts and Pages and returned deleted images that caused broken links.

**Comment by mindreeper2420** [comment]
Looking for thoughts on different pagination styles.

The first is a basic "New" / "Old" style, with page X of Y in the middle.
screen shot 2018-07-13 at 2 42 40 pm
screen shot 2018-07-13 at 2 42 45 pm
screen shot 2018-07-13 at 2 42 50 pm

The second displays all of the pages by number, allowing the user to jump to a specific page (though they do not know what is on that page until they see it).
- variation 1
screen shot 2018-07-13 at 2 47 18 pm
screen shot 2018-07-13 at 2 47 32 pm
screen shot 2018-07-13 at 2 47 26 pm

- variation 2
screen shot 2018-07-13 at 2 45 41 pm
screen shot 2018-07-13 at 2 48 09 pm
screen shot 2018-07-13 at 2 45 24 pm

**Comment by rmohr** [comment]
Will the user-guide also be prominently linked?

**Comment by rmohr** [comment]
I would have expected that the `Docs` section **is** the [user-guide](https://kubevirt.io/user-guide/#/). Except with maybe different css style.

**Comment by mindreeper2420** [comment]
@rmohr we're still discussing how to best handle the user guide - whether to incorporate it fully into the kubevirt.io site (not as a separate subdomain), or put some highlights and then link off to the full documentation.

**Comment by fabiand** [comment]
> whether to incorporate it fully into the kubevirt.io site (not as a separate subdomain),

I suppose this is meant in the sense of displaying it in the conext of the website.
But _not_ in the sense of "merging the content" into the website.
Correct?

Just making sure, as the user-guide is a separately consumable piece.

**Comment by aglitke** [comment]
Great update!  

- I like the new kubevirt logo.  It would be nice to see it larger on the main landing page

**Comment by mindreeper2420** [comment]
@fabiand That is the question - is the current user guide site moved into this (as there is a docs section), or are the primary areas (Installation, Usage, Workload, Authorization and Additional Resources) are just used as direct links into the user guide.

I've recently pushed an update for the **Installation** and **Additional Resources** sections that are the opener of that section, but then link to the user guide at the end. There is also now a link directly to the User Guide from the Docs sidebar.

**Comment by rmohr** [comment]
I don't see the reason for a duplicate docs section at all. Why can't "Docs" point to the user-guide?

**Comment by scollier** [comment]
@jasonbrooks Please see the conversation here about the user guide.

**Comment by jasonbrooks** [comment]
For now, we can have docs nav item link to the user guide, and then move to integrate them as a second step.

I took a look at putting the user guide into the main site, like this: http://kubevirtgithubio-kubevirt-test.6923.rh-us-east-1.openshiftapps.com/docs/introduction/, it's in my fork at https://github.com/jasonbrooks/kubevirt.github.io/tree/docs. We can do something like this to integrate the docs.

**Comment by scollier** [comment]
@mindreeper2420 @jasonbrooks I think the integration of the docs looks great.  Nice work there.

**Comment by mindreeper2420** [comment]
@scollier This is all set for merging. I've rebased the commits down to one and have finished the design reviews.

**Comment by fabiand** [comment]
@mindreeper2420 thank you very much!

Please let's make some noise.

Side note - maybe we can update the style of the user-guide to be more aligned with the web site.

**Pull request merged**
