### PR TITLE
Fix check_spelling exit codes plus a couple cosmetics

### LINKED ISSUE #742: No exit code for make check_spelling
/kind bug

There's been some enhancement to Makefile in the last few months.  Somewhere along the line we lost the exit code for `make check_spelling`.  This is a highly sensitive area of the code.  I suggest we bring back code from [e4a4c89c](https://github.com/kubevirt/kubevirt.github.io/commit/e4a4c89cb4ee9212db9ff709197cd0be9162866c#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52)

### PR DESCRIPTION
**Pull request by mazzystr**
**What this PR does / why we need it**:
FIXES #742 

**Special notes for your reviewer**:
Run `make check_spelling`
1) Initial test should fail with many spell checks.  `echo $?` should return 2 which will be the same as the Makefile error
2) Update Line159 and invalidate url.  `echo $?` should return 2 which will be the same as the Makefile error
3) Update Line159 and invalidate filename.  `echo $?` should return 2 which will be the same as the Makefile error
4) Update local yaspeller,json file with errors from above (this is gonna be painful ...) and then `rm -rf ./README.md`.  `make check_spelling` should complete successfully.  `echo $?` should return 0.

### CODE REVIEW

**Comment by mazzystr** [comment]
@davidvossel Sorry to bug ya.  We gotta get this right in order to leave travis-ci.

**Comment by cwilkers** [comment]
/lgtm

check_spelling with an error returns Error 2

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
