### PR TITLE
Windows 11 installation blog post

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
This is a first attempt at documenting Windows 11 installation.
There's a probably a lot to improve, in both the format and the content, so please don't hold back in your review!

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mazzystr** [comment]
Looks good to me at glance

/lgtm

@jobbler Do you have time to roll through this with a deeper check?

**Comment by fossedihelm** [comment]
Thanks @jean-edouard It looks brilliant! How about adding a note specifying that `tpm`,  `smm` and `secureBoot` are required for Windows 11? Do you think it will be out of scope? Thanks

**Comment by jean-edouard** [comment]
> Thanks @jean-edouard It looks brilliant! How about adding a note specifying that `tpm`, `smm` and `secureBoot` are required for Windows 11? Do you think it will be out of scope? Thanks

Good idea, thank you! I just added a note about it, updated the date to next Monday and force-pushed.

**Comment by fossedihelm** [comment]
> > Thanks @jean-edouard It looks brilliant! How about adding a note specifying that `tpm`, `smm` and `secureBoot` are required for Windows 11? Do you think it will be out of scope? Thanks
> 
> Good idea, thank you! I just added a note about it, updated the date to next Monday and force-pushed.

@jean-edouard Thanks! 
/lgtm

**Comment by aburdenthehand** [comment]
@jean-edouard - Looks like this was approved a while ago but never merged. Did you want to update the date again and we can tag an approver to get this merged?

**Review by stu-gott — COMMENTED** [review]
/lgtm

**Pull request merged**
