### PR TITLE
css updates

### LINKED ISSUE #263: New blog posts are hidding inside 'blog' section giving no visibility
For the casual visitor, new blog posts are not featured in the website, a sidebar on the front page containing latest posts could be a good addition.

### LINKED ISSUE #333: Separate css styles from html tags
image
https://www.dareboost.com/en/report/d_15d77414a90b99843ddb4b7a1?reportIds=d_15d77414a90b99843ddb4b7a1

### LINKED ISSUE #598: Jekyll triggering warning with content
/kind bug

```
    Liquid Warning: Liquid syntax error (line 113): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 203): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 364): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 388): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 401): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 417): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 450): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 465): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /srv/jekyll/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
    Liquid Warning: Liquid syntax error (line 42): [:dot, "."] is not a valid expression in "year in (startYear...endYear) reversed" in pages/blogs/date.md
    Liquid Warning: Liquid syntax error (line 50): [:dot, "."] is not a valid expression in "month in (1...12) reversed" in pages/blogs/date.md
    Liquid Warning: Liquid syntax error (line 55): [:dot, "."] is not a valid expression in "postIndex in (currentPostIndex...lastPostIndex)" in pages/blogs/date.md
    Liquid Warning: Liquid syntax error (line 103): [:dot, "."] is not a valid expression in "year in (startYear...endYear) reversed" in pages/blogs/date.md
    Liquid Warning: Liquid syntax error (line 107): [:dot, "."] is not a valid expression in "month in (1...12) reversed" in pages/blogs/date.md
    Liquid Warning: Liquid syntax error (line 112): [:dot, "."] is not a valid expression in "postIndex in (currentPostIndex...lastPostIndex)" in pages/blogs/date.md
```

Please fix so we have clean content generation

### LINKED ISSUE #599: Beautify action buttons
/kind enhancement

We have a lovely logo and color theme yet action buttons colored orange .  They shout warning! and danger!

Can we get an update to them?

### PR DESCRIPTION
**Pull request by matthewcarleton**
closes #599 
closes #333 
closes #263
also just cleans up some images and adds a bit of accessibility enhancements

### CODE REVIEW

**Comment by mazzystr** [comment]
Please rebase and add `-s` to the git command

**Comment by mazzystr** [comment]
re #333 ... Prow [build log](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt.github.io/604/kubevirt-io-presubmit-link-checker/1290306885542481920) still shows Liquid warning with content

**Comment by matthewcarleton** [comment]
> re #598 ... Prow [build log](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt.github.io/604/kubevirt-io-presubmit-link-checker/1290306885542481920) still shows Liquid warning with content

whoops I meant #599

**Comment by codificat** [comment]
Travis build was failing, apparently due to an old version of Ruby being used. I added a commit to update that version and it builds fine now. Also took a quick look at the [rendered changes](https://deploy-preview-604--kubevirtio.netlify.app/) and at first sight they
/lgtm
thanks!

**Comment by codificat** [comment]
/assign mazzystr
for a proper review and approval

**Comment by mazzystr** [comment]
Closing this pull and moving  it to mazzystr fork branch uxd for controlled packaging and release

/close

**Pull request closed without merging**
