### PR TITLE
Fixed emulation configmap command

### PR DESCRIPTION
**Pull request by slintes**

### CODE REVIEW

**Comment by rmohr** [comment]
I am confused now. Are the docs still coming from this page? I thought that docs are now again in the user-guide? @fabiand @slintes ?

**Comment by fabiand** [comment]
No, the docs stay in the user-guide.

**Comment by rmohr** [comment]
Ok, so this PR should be reopend in the user-guide and the whole docs directory here should be deleted?

**Comment by fabiand** [comment]
The PR should be reopened.

Let's not delete the docs/ dir here until we know how everything converges.

**Comment by slintes** [comment]
oh, ok, will search for the right place for a new PR :)

**Pull request closed without merging**
