### PR TITLE
Added SIG - Performance & Scale Playlist to community meetings section

### PR DESCRIPTION
**Pull request by ansijain**
Signed-off-by: ansijain <ansi.jain@india.nec.com>

**What this PR does / why we need it**: To Add SIG - Performance & Scale Playlist to community meetings section.

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes https://github.com/kubevirt/kubevirt.github.io/issues/801

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mazzystr** [comment]
Hi Ansi, It may just be me and my Monday morning haze but I don't see the changes in [preview](https://deploy-preview-803--kubevirtio.netlify.app/community/)

**Comment by ansijain** [comment]
> Hi @ansijain , It may just be me and my Monday morning haze but I don't see the changes in [preview](https://deploy-preview-803--kubevirtio.netlify.app/community/)

Hi @mazzystr 

Please refer to image below. On the right hand side I have added SIG - Performance & Scale Playlist

Screenshot from 2021-10-04 20-53-46
r

**Comment by mazzystr** [comment]
Yup, Monday morning haze!  I was looking at the Community tab, LOL!

The update looks great!  Thank you for the contribution!

**Pull request merged**
