### PR TITLE
Replacing complicated latest version commands with simple curl

### LINKED ISSUE #891: Deployment code block doesn't filter alpha releases
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When deploying KubeVirt using the code block provided in the quick start guides, alpha releases aren't filtered.

**What you expected to happen**:

When deploying using the sample code blocks, only stable releases are deployed.

**Anything else we need to know?**:

Sample code block that doesn't filter alpha releases:

```
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
```

Suggested alternate code block to filter alpha releases, assuming all tag_names are SemVer compliant:

```
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-.*$' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
```

Affected guides:

1. https://kubevirt.io/quickstart_kind/
2. https://kubevirt.io/quickstart_cloud/

### PR DESCRIPTION
**Pull request by cwilkers**
**What this PR does / why we need it**:

Replace complicated multi-command pipeline to get latest stable version string with an easy curl in our quickstart documentation.

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

Fixes #891 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cwilkers** [comment]
Hi @fabiand @dhiller @dankenigsberg @0xFelix @aburdenthehand ,

I just added you as reviewers because I think this is a deceptively important Intro to KubeVirt kind of issue.

Our tooling seems to support a very concise and easy way to determine the latest version of KubeVirt that solves a number of problems, some of which have been raised in recent issues.

I'm hoping to answer one big questions by inviting so many busy (but highly involved) people as reviewer:

1. Is this a sustainable way to get the stable version? i.e. are we taking advantage of a side-effect that may go away in the future due to changes in the CI processes?

Advantages:

1. I have seen recent blog posts using this command instead of the convoluted one in our intros, and thought, "Why aren't we presenting this in our labs?"
2. Older ways involved multi-pipe bash commands in a `$()` setup that would make a greybeard Un*x admin shed a tear of pride, but may make newer users flee in horror
3. The new method here avoids alpha and -rcX releases so our demo and 101 content will work on latest stable versions only. #891 
4. Our minikube plugin is currently broken (in a way that sadly this does not fix) but simplifying the curl statement will certainly help. See https://github.com/kubernetes/minikube/issues/15918 for why minikube is broken.

Thank you all for your time!

**Comment by dankenigsberg** [comment]
Few notes.
* I don't really mind having a multipipe to extract the version. Note that my beard *is* grey.
* I don't know what generates https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt and if it can be trusted to stay up-to-date forever. @brianmcarey may know.
* I find it less nice to depend on an external service; but we're "married" so strongly to Prow anyway that adding this is does not matter.
* The multipipe is buggy. `sort -r` says that 1.9 is newer than 1.10. If you keep the multipipe, make it `sort -rV`.

**Comment by 0xFelix** [comment]
I agree, we should make this commandline a bit friendlier. :)

And since we are currently using the GitHub API, may I throw in the following?

`curl -s https://api.github.com/repos/kubevirt/kubevirt/releases/latest | jq -r '.tag_name'`

If we don't want to rely on Prow this looks to be the easiest solution to me.

**Comment by brianmcarey** [comment]
>     * I don't know what generates https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt and if it can be trusted to stay up-to-date forever. @brianmcarey may know.
> 

That stable.txt file is updated as part of the release process so I think it is ok to rely on this. The release will not be created successfully if this file is not updated. 

https://github.com/kubevirt/kubevirt/blob/d41b6ddb20837e4445a899be0dc492bde25beb26/automation/release.sh#L91

**Comment by aburdenthehand** [comment]
/lgtm
@0xFelix That is a nice and concise command you've got there :) I like it. One nit (from my writer days) is that `jq` isn't included by default and could be an additional install for some folks. 

From Brian's comment this source seems sufficiently reliable, and the simplicity is attractive.

**Comment by dhiller** [comment]
What @brianmcarey said.

Also we are advertising this URL in the installation section of our user-guide: https://kubevirt.io/user-guide/operations/installation/#installing-kubevirt-on-kubernetes

So it will not go away and should be as reliable as google cloud storage is.... Besides that, if GCS is not working, prow will not be working.

**Comment by 0xFelix** [comment]
I'd vote to keep the GCS curl. Looks to be the most compatible, easy to understand and robust solution.

/lgtm

**Review by 0xFelix — APPROVED** [review]

**Comment by cwilkers** [comment]
I think there's a consensus here, I'll go ahead and ...
/approve

**Pull request merged**
