### PR TITLE
Removing NoVNC blog

### PR DESCRIPTION
**Pull request by aburdenthehand**
The NoVNC component has been identified as vulnerable and that this blog shows how to bypass authentication.
@fabiand @rmohr

### CODE REVIEW

**Comment by rmohr** [comment]
/approve

Probably some stale links still included from CI results?

**Comment by aburdenthehand** [comment]
Good point, it had some links to it in a UI blog.
That blog is also out of date but I don't think it's worth removing. I've dropped the lines containing the xrefs but have not removed the noVNC section from the UI blog.

**Pull request merged**
