### PR TITLE
fix: get_kubevirt guide

### PR DESCRIPTION
**Pull request by tripledes**
* Rename it to quickstart_minikube
* Change references from get_kubevirt to quickstart_minikube
* Remove "Try it!" on existing k8s cluster from front page, can be
readded it later
* Remove *advanced* stuff, belongs somewhere else
* Reorder and split scriptlets so they are 1 command
* Remove cni stuff for minikube not needed on latest versions

### CODE REVIEW

**Comment by tripledes** [comment]
Didn't realize we had such a dependency on the front page.

I'd still go to keep the Kubernetes instructions in a different guide, naming:

* quickstart_minikube.md
* quickstart_kubernetes.md

**Comment by markllama** [comment]
notes:

- Specify that this uses minikube with kvm (no Virtualbox
- note that on CentoOS or RHEL, use minikube 0.35.0, but docker-machine-driver-kvm2 version 0.31.0
- Fedora 29 works with minikube 0.35.0 for both minikube and kvm2 driver
- add checks for pods in kube-system namespace all running?
- after installing kubevirt operator and cr, add checks for pods in kubevirt namespace?
- remove start/stop testvm and link to lab1 instead?

**Comment by tripledes** [comment]
> notes:
> 
> * Specify that this uses minikube with kvm (no Virtualbox)

Lines 17-19 mention Linux and the driver KVM2, if that's not enough I can reword it :)

> * note that on CentoOS or RHEL, use minikube 0.35.0, but docker-machine-driver-kvm2 version 0.31.0

Any reference to the limitation? I wasn't aware of any.

> * Fedora 29 works with minikube 0.35.0 for both minikube and kvm2 driver
> * add checks for pods in kube-system namespace all running?

Yes, I was pondering this, would it be of any use for testing it having the expected output on files? If not, I think I'd just add *shell* snippets with the output.

> * after installing kubevirt operator and cr, add checks for pods in kubevirt namespace?
> * remove start/stop testvm and link to lab1 instead?

Let me check the lab1, if the contents is duplicated we might need to reconsider this page.

**Comment by markllama** [comment]
RE: KVM: I think  a statement "this process assumes minikube with kvm2" would remove any ambiguity  I'll look at thcurrent.
Re output, especially for async steps: Some kind of output (not in a sciptlet) showing what to expect before and after complete.  Ie all pods in indicate "running" would help.

The rest is great and I think should go ahead.  We can tweak over time.

**Comment by tripledes** [comment]
Should be ready for reviewing and merging.

**Pull request merged**
