### PR TITLE
Last cleanup of offensive language.

### PR DESCRIPTION
**Pull request by cwilkers**
Signed-off-by: cwilkers <cwilkers@redhat.com>

Last Fixes for #726

### CODE REVIEW

**Comment by cwilkers** [comment]
@mazzystr @dhiller 
I would like a sanity check that the removal of the publish-travis script in `package.json` should not affect anything as Travis has been retired.

Perhaps in a separate PR, we can look at removing more of the Travis specific infrastructure as technical debt.

**Comment by dhiller** [comment]
> @mazzystr @dhiller I would like a sanity check that the removal of the publish-travis script in `package.json` should not affect anything as Travis has been retired.
> 
> Perhaps in a separate PR, we can look at removing more of the Travis specific infrastructure as technical debt.

Travis CI has been disabled on Dec 1st 2021 for the whole org. I think you can remove everything related to Travis. But yes, in a new PR SGTM.

**Review by dhiller — COMMENTED** [review]
/approve

**Review by dhiller — APPROVED** [review]
/hold

Remove hold when you see fit.

**Comment by mazzystr** [comment]
package.json can be removed completely since we moved everything to Prow.

The project-infra ci and post submit jobs need to be checked to ensure it
does not reference master.

Tthe README for this repo likely needs updating

**Pull request merged**
