### PR TITLE
Adding arm to index page as end-user per KubeVirt ADOPTERS

### LINKED ISSUE #812: Obtain permission to advertise ARM on index page
/kind enhancement

**What happened**:
Let's find the ARM representative and obtain explicit permission to advertise.  

**What you expected to happen**:

**Anything else we need to know?**:
Add logo [here](https://github.com/kubevirt/kubevirt.github.io/tree/master/assets/images/adopters)
Add data [here](https://github.com/kubevirt/kubevirt.github.io/blob/master/_data/adopters.yml)

### PR DESCRIPTION
**Pull request by mazzystr**
/kind enhancement
/label website

**What this PR does / why we need it**:
Adding arm to index page as end-user per KubeVirt ADOPTERS

Fixes #812

### CODE REVIEW

**Comment by mazzystr** [comment]
@zhlhahaha Url for review for logo use compliance is here .... https://deploy-preview-815--kubevirtio.netlify.app/

Please comment lgtm and approve.  

Then I will have a maintainer add the merge tag.  Thanks!

**Comment by zhlhahaha** [comment]
> @zhlhahaha Url for review for logo use compliance is here .... https://deploy-preview-815--kubevirtio.netlify.app/
> 
> Please comment lgtm and approve.
> 
> Then I will have a maintainer add the merge tag. Thanks!

Ok, would it be better to put the source of Arm logo in the comments?

**Comment by mazzystr** [comment]
Source of the logo was from the arm corp logo usage page.

Usually I copy the img with the website code.  Then the img is served by
GitHub Pages.  There have been complaints in the past that our website adds
undue bandwidth load on customers' servers.

**Comment by zhlhahaha** [comment]
Ok,
/approve
/lgtm

**Comment by mazzystr** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
