### PR TITLE
Update page layout to shrink side menu width

### LINKED ISSUE #590: Blog/lab side bar take too much screen real estate
/kind bug

Goal: Adjust side menu

Problem: Side menu consumes 30% of the window real estate

Why is this important: The page looks right side heavy and there is a lot of dead space.

 
This should be fixed easily enough with a css adjustment

Ref: [KNIECO-2251](https://issues.redhat.com/browse/KNIECO-2251)

### PR DESCRIPTION
**Pull request by mindreeper2420**
**What this PR does / why we need it**:

Reconfigure the page layouts for the Blog, Lab, and Video pages to use a wider container, as well as adjusted column widths.

Signed-off-by: Adam Jolicoeur <mindreeper2420@gmail.com>

**Does this PR fix any issue?**
> Fixes #590

**Special notes for your reviewer**:
Blogs_XLarge
Labs_Large
Labs_Medium
Labs_XLarge
Labs_XXLarge
Videos

### CODE REVIEW

**Comment by mazzystr** [comment]
@mindreeper2420  think you can sneak the fix for issues/591 into this pull also?

**Comment by mindreeper2420** [comment]
@mazzystr I'd rather keep them separate, in case a rollback needs to take place. That'd be easier than having to cherry-pick commits out.

**Comment by codificat** [comment]
I think that the change proposed in this PR is also part of #612 (preview of that available [here](https://deploy-preview-612--kubevirtio.netlify.app/blogs/)), correct?

@mazzystr can you confirm?

**Comment by mazzystr** [comment]
This

> I think that the change proposed in this PR is also part of #612 (preview of that available [here](https://deploy-preview-612--kubevirtio.netlify.app/blogs/)), correct?
> 
> @mazzystr can you confirm?

Yes that is correct.  I'm closing this pull.

**Pull request closed without merging**
