### PR TITLE
Unify minikube with other labs format and remove trailing files

### PR DESCRIPTION
**Pull request by iranzo**

### CODE REVIEW

**Comment by iranzo** [comment]
Just in case:

~~~
 iranzo  ~  Descargas  130  kubectl create -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/pvc_fedora.yml
Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/pvc_fedora.yml": persistentvolumeclaims "fedora" is forbidden: Internal error occurred: 2 default StorageClasses were found

~~~

CDI lab seems to fail, vm lab is exactly the same one as minikube so it works

**Comment by karmab** [comment]
does it still apply ?

**Comment by iranzo** [comment]
Yes, it does

**Pull request merged**
